#CÓDIGO EXIBE NA TELA SE DOIS NÚMEROS INTEIROS SÃO DIFERENTES (TRUE/FALSE) 
numero1 = int(input("Informe número 1: "))
numero2 = int(input("Informe número 2: "))
print ("São diferentes ?")
print (numero1 != numero2)